name: test_go

on:
  push:
    branches:
    - master
    - staging
    - main

jobs:
  Test:
    name: Test code
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - uses: docker/build-push-action@v2
      with:
        tags: test-image:latest
        push: false
    - name: Test code
      uses: addnab/docker-run-action@v3
      with:
        image: test-image:latest
        run: |
          go test ./...
  Version:
    name: Calculate Version
    needs: [Test]
    runs-on: ubuntu-latest
    outputs:
      repo_version_env: ${{ steps.version.outputs.repo_tag }}
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: Calculate version
      id: version
      uses: ./
  Push_Tag:
    name: Push New Tag
    needs: [Test, Version]
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: Push version
      run: |
        git tag ${{ needs.Version.outputs.repo_version_env }}
        git push --tags