name: test_go

on:
  push:
    branches:
    - master
    - staging
    - main

jobs:
  Test:
    name: Test code
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - uses: docker/build-push-action@v2
      with:
        tags: test-image:latest
        push: false
    - name: Test code
      uses: addnab/docker-run-action@v3
      with:
        image: test-image:latest
        run: |
          go test ./...